
import Main from '@/components/Main'
import Head from 'next/head'
import { useState } from 'react'

export default function Home() {
  const [style, setStyle] = useState('')
  console.log(style)

  const styleHandler = () => {
    setStyle("green")
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Main />
      </main>
    </>
  )
}

